<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWinUI>true</UseWinUI>
    <RootNamespace>Lumiere.Overlay</RootNamespace>
    <AssemblyName>Lumiere.Overlay</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <ProjectReference Include="..\Lumiere.Graphics\Lumiere.Graphics.csproj" />
    <ProjectReference Include="..\Lumiere.Infrastructure\Lumiere.Infrastructure.csproj" />
  </ItemGroup>
</Project>

