<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Lumiere.Windows.Host</RootNamespace>
    <AssemblyName>Lumiere.Windows.Host</AssemblyName>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumiere.Windows.Capture\Lumiere.Windows.Capture.csproj" />
    <ProjectReference Include="..\Lumiere.Windows.Graphics\Lumiere.Windows.Graphics.csproj" />
  </ItemGroup>
</Project>
