<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
    <PackageVersion Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageVersion Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>
</Project>

