<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Lumiere.Infrastructure</RootNamespace>
    <AssemblyName>Lumiere.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" />
    <PackageReference Include="Vortice.DXGI" />
  </ItemGroup>
</Project>

