<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Lumiere.Graphics</RootNamespace>
    <AssemblyName>Lumiere.Graphics</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" />
    <PackageReference Include="Vortice.DXGI" />
    <ProjectReference Include="..\Lumiere.Infrastructure\Lumiere.Infrastructure.csproj" />
  </ItemGroup>
</Project>

