<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Lumiere.Capture</RootNamespace>
    <AssemblyName>Lumiere.Capture</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumiere.Graphics\Lumiere.Graphics.csproj" />
    <ProjectReference Include="..\Lumiere.Infrastructure\Lumiere.Infrastructure.csproj" />
  </ItemGroup>
</Project>

