<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Lumiere.Windows.Capture</RootNamespace>
    <AssemblyName>Lumiere.Windows.Capture</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumiere.Windows.Graphics\Lumiere.Windows.Graphics.csproj" />
    <ProjectReference Include="..\Lumiere.Windows.Interop\Lumiere.Windows.Interop.csproj" />
  </ItemGroup>
</Project>
